name: Deploy to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Packages to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Setup - Checkout
      uses: actions/checkout@v3

    - name: Setup - Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy Package
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./dist/package.json
        access: public
